# Generated by Django 5.1.1 on 2024-10-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('first_age', models.FloatField()),
                ('last_age', models.FloatField()),
                ('product_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('age_group', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image_url', models.URLField(max_length=500)),
                ('sizes', models.CharField(max_length=200)),
                ('colors', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('pattern', models.CharField(max_length=200)),
                ('nice_to_know', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('face_image', models.TextField()),
                ('face_embedding', models.TextField()),
                ('username', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=200)),
                ('sleeve_length', models.CharField(max_length=200)),
                ('neckline', models.CharField(max_length=200)),
                ('fit', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heel_height', models.CharField(max_length=100)),
                ('additional_description', models.CharField(max_length=200)),
                ('footwear_style', models.CharField(max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
    ]
